version: "3.8"

services:
  jenkins:
    container_name: jenkins-dind
    image: jenkins-dind
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
